version: '3.8'
services:
  wordpress:
    build: 
      context: ./.docker/wordpress/
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - ${PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PWD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 0
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TBL_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('SCRIPT_DEBUG', true);
    volumes:
      - wordpress:/var/www/html/
      - ./src/themes/:/var/www/html/wp-content/themes/
      - ./src/plugins/:/var/www/html/wp-content/plugins/

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PWD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PWD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql 
      - PMA_USER=${WORDPRESS_DB_USER}
      - PMA_PASSWORD=${WORDPRESS_DB_PWD}

  wpcli:
    image: wordpress:cli
    links:
      - mysql:mysql
    tty: true
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --locale=${WORDPRESS_LOCALE} --url="${DOMAIN}:${PORT}" --title="${WORDPRESS_BLOG_NAME}" --admin_user=${WORDPRESS_ADMIN_LOGIN} --admin_password=${WORDPRESS_ADMIN_PWD} --admin_email=${WORDPRESS_ADMIN_EMAIL};
      '
    user: xfs
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PWD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      mysql:
        condition: service_healthy
      wordpress:
        condition: service_started

volumes:
  wordpress:
  db:
